name: Create train arrivals dataset workflow
run-name: ${{ github.actor }} is creating a new train arrivals dataset
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: "25"

      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out CFR api adapter
        uses: actions/checkout@v6
        with:
          repository: "Stavre/cfr-api-adapter"
          path: "cfr-api-adapter"

      - name: Check out CFR data aggregator
        uses: actions/checkout@v6
        with:
          repository: "Stavre/cfr-data-aggregator"
          path: "cfr-data-aggregator"

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Starting CFR api adapter backend
        run: ./gradlew bootRun
        working-directory: ./cfr-api-adapter

      - name: Creating dataset using CFR data aggregator
        run: ./gradlew bootRun --args="export-arrivals"
        working-directory: ./cfr-data-aggregator

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."